<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Вывод</a>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
# импортируем необходимые библиотеки
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

pd.options.mode.chained_assignment = None

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Сброс ограничений на количество выводимых рядов
pd.set_option('display.max_rows', None)

# Сброс ограничений на число столбцов
pd.set_option('display.max_columns', None)

# Сброс ограничений на количество символов в записи
pd.set_option('display.max_colwidth', None)

In [3]:
df = pd.read_csv('/datasets/insurance.csv')
#df = pd.read_csv('insurance.csv')

Изучим данные:

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [5]:
df.head(10)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
5    1     43.0   41000.0            2                  1
6    1     39.0   39700.0            2                  0
7    1     25.0   38600.0            4                  0
8    1     36.0   49700.0            1                  0
9    1     32.0   51700.0            1                  0

In [6]:
df.describe()

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

Сделаем типом данных всех столбцов целочисленный:

In [7]:
df['Возраст'] = df['Возраст'].astype('int')
df['Зарплата'] = df['Зарплата'].astype('int')

Проверим, есть ли дубликаты в таблице:

In [8]:
df.duplicated().sum()

153

In [9]:
df[df.duplicated(keep=False)]

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
3       0       21     41700            2                  0
24      0       21     40400            3                  0
52      1       29     42400            0                  0
59      1       30     49900            1                  0
63      0       32     43800            1                  0
68      1       20     37400            2                  0
69      1       39     48100            1                  0
80      1       41     32700            0                  0
82      0       31     37400            2                  0
88      1       24     33100            1                  0
103     0       27     46800            2                  0
107     1       24     53900            2                  0
119     0       22     33800            1                  0
121     1       19     43200            1                  0
134     1       41     34000            1                  0
144     0       25     52800            2                  0
169     1       38     40700            1                  0
176     1       41     48900            0                  0
204     0       26     46700            0                  0
209     0       22     40100            1                  0
217     1       29     45600            1                  0
219     0       29     49900            2                  0
223     1       34     37500            1                  0
248     0       31     49400            1                  0
274     0       25     43400            0                  0
281     1       39     48100            1                  0
312     1       33     43700            2                  0
324     1       35     42500            0                  0
333     0       32     25600            1                  0
361     0       50     24700            1                  2
378     0       35     44000            1                  0
406     1       36     41300            0                  0
411     1       24     32900            1                  0
412     1       30     43000            0                  0
421     1       22     42700            1                  0
471     1       30     28200            0                  0
476     1       32     36900            0                  0
488     1       24     32900            1                  0
489     1       22     32600            1                  0
503     1       28     41100            0                  0
513     0       31     37400            2                  0
552     0       25     47800            1                  0
568     1       27     37300            0                  0
636     0       26     36100            1                  0
664     1       19     35500            0                  0
668     0       25     45900            1                  0
677     0       37     51400            0                  0
678     1       33     40900            1                  0
683     1       24     35300            0                  0
688     0       20     35800            0                  0
712     1       19     52600            0                  0
718     1       22     32600            1                  0
720     0       25     28300            0                  0
721     0       37     37300            1                  0
731     1       19     35600            2                  0
747     0       33     41500            1                  0
773     0       21     35300            1                  0
778     0       23     53600            1                  0
785     0       20     35800            0                  0
843     1       31     37200            1                  0
851     0       19     51700            0                  0
857     1       23     43400            1                  0
869     1       24     33100            1                  0
887     1       19     35500            0                  0
896     1       25     33400            1

Удалим дубликаты:

In [10]:
df.drop_duplicates(inplace=True)

Проверим наличие пропусков:

In [11]:
display(df.isna().sum())

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4847 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Пол                4847 non-null   int64
 1   Возраст            4847 non-null   int64
 2   Зарплата           4847 non-null   int64
 3   Члены семьи        4847 non-null   int64
 4   Страховые выплаты  4847 non-null   int64
dtypes: int64(5)
memory usage: 227.2 KB


### Вывод

Были загружены и проанализированы данные:

* Все столбцы приведены к целочисленному типу;
* Пропусков нет;
* Дубликаты удалены.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Вопрос:** Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)

**Ответ:** Не изменится.

**Обоснование:** 

Новая матрица признаков: $Y = XP,$ где $P$ - произвольная обратимая матрица

При преобразовании воспользуемся свойствами матриц: $ (AB)^T = B^T A^T$, $ (AB)^{-1} = B^{-1} A^{-1}$ (Матрицы квадратные)

Преобразуем формулу весов: $ w' = (Y^T Y)^{-1} Y^T y = ((XP)^T XP)^{-1} (XP)^T y = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y $

Умножение матрицы и обратной матрицы равно единичной матрице: $ A A^{-1} = E $, тогда $ w' = P^{-1} (X^T X)^{-1} E X^T y $

Если любую матрицу X умножить на единичную (или наоборот), получится эта же матрица X: $ w' = P^{-1} (X^T X)^{-1} X^T y $

Формула для предсказаний: $ a' = XPw'$

Подставим полученную формулу для $w'$, тогда $ a' = XP P^{-1} (X^T X)^{-1} X^T y = X (X^T X)^{-1} X^T y = Xw$, значит $a' = a $

### Вывод

Качество линейной регрессии не изменится при умножении признаков на обратимую матрицу.

## Алгоритм преобразования

**Алгоритм**

1. Создадим случайную обратимую матрицу $P$.
2. Проверим, что матрица обратима.
3. Получим новую матрицу, умножив $XP$.
4. Применим новую матрицу на модели.

**Обоснование**

Чтобы вернуться к матрице $X$, нужно умножить новую матрицу на $P^{-1}$.

Матрица $P$ должна быть квадратной (размер $nxn$), в данной задаче n=4.

## Проверка алгоритма

Разделим данные на признаки и целевой признак:

In [13]:
features = df.drop('Страховые выплаты', axis=1)
target = df['Страховые выплаты']

Создадим квадратную матрицу со случайнми числами:

In [15]:
np.random.seed(12345)
n = 4
matrix_pr = np.random.sample((n,n))

print(matrix_pr)

[[0.92961609 0.31637555 0.18391881 0.20456028]
 [0.56772503 0.5955447  0.96451452 0.6531771 ]
 [0.74890664 0.65356987 0.74771481 0.96130674]
 [0.0083883  0.10644438 0.29870371 0.65641118]]


Проверим, обратима ли случайная матрица:

In [16]:
np.linalg.inv(matrix_pr)

array([[ 2.1336149 ,  0.5051926 , -1.71113385,  1.33832486],
       [-3.76534462, -2.61352053,  6.72316006, -6.07193701],
       [ 0.97426298,  2.9928115 , -3.49875049,  1.84220045],
       [ 0.13998298, -0.94454066,  0.52375812,  1.652661  ]])

Зашифруем данные, умножив матрицу признаков на матрицу со случайными числами:

In [17]:
features_pr = features @ matrix_pr
features_pr.head(10)

0             1             2             3
0  37169.983952  32441.905747  37126.682258  47708.455342
1  28484.575966  24863.156593  28457.829124  36560.358528
2  15743.503414  13742.238084  15729.981916  20206.383593
3  31241.345787  27266.582942  31200.559759  40101.520436
4  19563.289157  17075.165256  19542.546847  25108.599330
5  30730.530708  26822.502391  30698.562631  39443.180177
6  29754.681179  25970.479381  29722.675321  38190.868712
7  28922.952504  25243.427786  28887.283235  37125.599645
8  37242.035991  32504.285011  37196.631166  47801.320130
9  38737.578366  33809.042573  38688.202726  49721.320894

Создадим 2 модели и проверим значение r2 на шифрованных и не шифрованных данных:

In [18]:
features_train, features_test = train_test_split(features, test_size=0.25, random_state=12345)

In [19]:
target_train, target_test = train_test_split(target, test_size=0.25, random_state=12345)

In [20]:
features_train_pr, features_test_pr = train_test_split(features_pr, test_size=0.25, random_state=12345)

Модель без шифрования данных:

In [21]:
model = LinearRegression()
model.fit(features_train, target_train)
r2 = r2_score(target_test, model.predict(features_test))
print(f'R2 = {r2}')

R2 = 0.4230772761583642


Модель с шифрованием данных:

In [22]:
model_pr = LinearRegression()
model_pr.fit(features_train_pr, target_train)
r2_pr = r2_score(target_test, model_pr.predict(features_test_pr))
print(f'R2 = {r2_pr}')

R2 = 0.42307727615816537


Значение r2 отличается только после 15 знака.

Проверим, что при умножении на обратную матрицу случайной, получим первоначальную матрицу признаков:

In [23]:
matrix_o = features_pr.dot(np.linalg.inv(matrix_pr))

In [24]:
np.round(matrix_o) == np.round(features.values)

0     1     2     3
0     True  True  True  True
1     True  True  True  True
2     True  True  True  True
3     True  True  True  True
4     True  True  True  True
5     True  True  True  True
6     True  True  True  True
7     True  True  True  True
8     True  True  True  True
9     True  True  True  True
10    True  True  True  True
11    True  True  True  True
12    True  True  True  True
13    True  True  True  True
14    True  True  True  True
15    True  True  True  True
16    True  True  True  True
17    True  True  True  True
18    True  True  True  True
19    True  True  True  True
20    True  True  True  True
21    True  True  True  True
22    True  True  True  True
23    True  True  True  True
24    True  True  True  True
25    True  True  True  True
26    True  True  True  True
27    True  True  True  True
28    True  True  True  True
29    True  True  True  True
30    True  True  True  True
31    True  True  True  True
32    True  True  True  True
33    True  True  True  True
34    True  True  True  True
35    True  True  True  True
36    True  True  True  True
37    True  True  True  True
38    True  True  True  True
39    True  True  True  True
40    True  True  True  True
41    True  True  True  True
42    True  True  True  True
43    True  True  True  True
44    True  True  True  True
45    True  True  True  True
46    True  True  True  True
47    True  True  True  True
48    True  True  True  True
49    True  True  True  True
50    True  True  True  True
51    True  True  True  True
52    True  True  True  True
53    True  True  True  True
54    True  True  True  True
55    True  True  True  True
56    True  True  True  True
57    True  True  True  True
58    True  True  True  True
59    True  True  True  True
60    True  True  True  True
61    True  True  True  True
62    True  True  True  True
63    True  True  True  True
64    True  True  True  True
65    True  True  True  True
66    True  True  True  True
67    True  True  True  True
68    True  True  True  True
69    True  True  True  True
70    True  True  True  True
71    True  True  True  True
72    True  True  True  True
73    True  True  True  True
74    True  True  True  True
75    True  True  True  True
76    True  True  True  True
77    True  True  True  True
78    True  True  True  True
79    True  True  True  True
80    True  True  True  True
81    True  True  True  True
82    True  True  True  True
83    True  True  True  True
84    True  True  True  True
85    True  True  True  True
86    True  True  True  True
87    True  True  True  True
88    True  True  True  True
89    True  True  True  True
90    True  True  True  True
91    True  True  True  True
92    True  True  True  True
93    True  True  True  True
94    True  True  True  True
95    True  True  True  True
96    True  True  True  True
97    True  True  True  True
98    True  True  True  True
99    True  True  True  True
100   True  True  True  True
101   True  True  True  True
102   True  True  True  True
103   True  True  True  True
104   True  True  True  True
105   True  True  True  True
106   True  True  True  True
107   True  True  True  True
108   True  True  True  True
109   True  True  True  True
110   True  True  True  True
111   True  True  True  True
112   True  True  True  True
113   True  True  True  True
114   True  True  True  True
115   True  True  True  True
116   True  True  True  True
117   True  True  True  True
118   True  True  True  True
119   True  True  True  True
120   True  True  True  True
121   True  True  True  True
122   True  True  True  True
123   True  True  True  True
124   True  True  True  True
125   True  True  True  True
126   True  True  True  True
127   True  True  True  True
128   True  True  True  True
129   True  True  True  True
130   True  True  True  True
131   True  True  True  True
132   True  True  True  True
133   True  True  True  True
134   True  True  True  True
135   True  True  True  True
136   True  True  True  True
137   T

### Вывод

Создана случайная матрица для шифрования признаков, а также сравнены значения R2 двух моделей: без шифрования признаков и с шифрованием.

Качество моделей различается после 15 знака, чем можно пренебречь (скорее это погрешность, т.к. случайная матрица состоит из чисел с плавающей точкой).

## Вывод

При умножении признаков на обратную матрицу качество линейной регрессии не изменяется, что было доказано теоретически, используя формулу расчета весов линейной регрессии, а также сравнив 2 модели линейной регрессии (первая не была умножена на обратную матрицу, вторая была умножена на обратную матрицу).