<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Вывод</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
# импортируем необходимые библиотеки
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

pd.options.mode.chained_assignment = None

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Сброс ограничений на количество выводимых рядов
pd.set_option('display.max_rows', None)

# Сброс ограничений на число столбцов
pd.set_option('display.max_columns', None)

# Сброс ограничений на количество символов в записи
pd.set_option('display.max_colwidth', None)

In [3]:
df = pd.read_csv('/datasets/insurance.csv')
#df = pd.read_csv('insurance.csv')

Изучим данные:

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [5]:
df.head(10)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
5    1     43.0   41000.0            2                  1
6    1     39.0   39700.0            2                  0
7    1     25.0   38600.0            4                  0
8    1     36.0   49700.0            1                  0
9    1     32.0   51700.0            1                  0

In [6]:
df.describe()

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

Сделаем типом данных всех столбцов целочисленный:

In [7]:
df['Возраст'] = df['Возраст'].astype('int')
df['Зарплата'] = df['Зарплата'].astype('int')

Проверим, есть ли дубликаты в таблице:

In [8]:
df.duplicated().sum()

153

In [1]:
#df[df.duplicated(keep=False)]

Удалим дубликаты:

In [10]:
df.drop_duplicates(inplace=True)

Проверим наличие пропусков:

In [11]:
display(df.isna().sum())

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4847 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Пол                4847 non-null   int64
 1   Возраст            4847 non-null   int64
 2   Зарплата           4847 non-null   int64
 3   Члены семьи        4847 non-null   int64
 4   Страховые выплаты  4847 non-null   int64
dtypes: int64(5)
memory usage: 227.2 KB


### Вывод

Были загружены и проанализированы данные:

* Все столбцы приведены к целочисленному типу;
* Пропусков нет;
* Дубликаты удалены.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Вопрос:** Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)

**Ответ:** Не изменится.

**Обоснование:** 

Новая матрица признаков: $Y = XP,$ где $P$ - произвольная обратимая матрица

При преобразовании воспользуемся свойствами матриц: $ (AB)^T = B^T A^T$, $ (AB)^{-1} = B^{-1} A^{-1}$ (Матрицы квадратные)

Преобразуем формулу весов: $ w' = (Y^T Y)^{-1} Y^T y = ((XP)^T XP)^{-1} (XP)^T y = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y $

Умножение матрицы и обратной матрицы равно единичной матрице: $ A A^{-1} = E $, тогда $ w' = P^{-1} (X^T X)^{-1} E X^T y $

Если любую матрицу X умножить на единичную (или наоборот), получится эта же матрица X: $ w' = P^{-1} (X^T X)^{-1} X^T y $

Формула для предсказаний: $ a' = XPw'$

Подставим полученную формулу для $w'$, тогда $ a' = XP P^{-1} (X^T X)^{-1} X^T y = X (X^T X)^{-1} X^T y = Xw$, значит $a' = a $

### Вывод

Качество линейной регрессии не изменится при умножении признаков на обратимую матрицу.

## Алгоритм преобразования

**Алгоритм**

1. Создадим случайную обратимую матрицу $P$.
2. Проверим, что матрица обратима.
3. Получим новую матрицу, умножив $XP$.
4. Применим новую матрицу на модели.

**Обоснование**

Чтобы вернуться к матрице $X$, нужно умножить новую матрицу на $P^{-1}$.

Матрица $P$ должна быть квадратной (размер $nxn$), в данной задаче n=4.

## Проверка алгоритма

Разделим данные на признаки и целевой признак:

In [13]:
features = df.drop('Страховые выплаты', axis=1)
target = df['Страховые выплаты']

Создадим квадратную матрицу со случайнми числами:

In [15]:
np.random.seed(12345)
n = 4
matrix_pr = np.random.sample((n,n))

print(matrix_pr)

[[0.92961609 0.31637555 0.18391881 0.20456028]
 [0.56772503 0.5955447  0.96451452 0.6531771 ]
 [0.74890664 0.65356987 0.74771481 0.96130674]
 [0.0083883  0.10644438 0.29870371 0.65641118]]


Проверим, обратима ли случайная матрица:

In [16]:
np.linalg.inv(matrix_pr)

array([[ 2.1336149 ,  0.5051926 , -1.71113385,  1.33832486],
       [-3.76534462, -2.61352053,  6.72316006, -6.07193701],
       [ 0.97426298,  2.9928115 , -3.49875049,  1.84220045],
       [ 0.13998298, -0.94454066,  0.52375812,  1.652661  ]])

Зашифруем данные, умножив матрицу признаков на матрицу со случайными числами:

In [17]:
features_pr = features @ matrix_pr
features_pr.head(10)

0             1             2             3
0  37169.983952  32441.905747  37126.682258  47708.455342
1  28484.575966  24863.156593  28457.829124  36560.358528
2  15743.503414  13742.238084  15729.981916  20206.383593
3  31241.345787  27266.582942  31200.559759  40101.520436
4  19563.289157  17075.165256  19542.546847  25108.599330
5  30730.530708  26822.502391  30698.562631  39443.180177
6  29754.681179  25970.479381  29722.675321  38190.868712
7  28922.952504  25243.427786  28887.283235  37125.599645
8  37242.035991  32504.285011  37196.631166  47801.320130
9  38737.578366  33809.042573  38688.202726  49721.320894

Создадим 2 модели и проверим значение r2 на шифрованных и не шифрованных данных:

In [18]:
features_train, features_test = train_test_split(features, test_size=0.25, random_state=12345)

In [19]:
target_train, target_test = train_test_split(target, test_size=0.25, random_state=12345)

In [20]:
features_train_pr, features_test_pr = train_test_split(features_pr, test_size=0.25, random_state=12345)

Модель без шифрования данных:

In [21]:
model = LinearRegression()
model.fit(features_train, target_train)
r2 = r2_score(target_test, model.predict(features_test))
print(f'R2 = {r2}')

R2 = 0.4230772761583642


Модель с шифрованием данных:

In [22]:
model_pr = LinearRegression()
model_pr.fit(features_train_pr, target_train)
r2_pr = r2_score(target_test, model_pr.predict(features_test_pr))
print(f'R2 = {r2_pr}')

R2 = 0.42307727615816537


Значение r2 отличается только после 15 знака.

Проверим, что при умножении на обратную матрицу случайной, получим первоначальную матрицу признаков:

In [23]:
matrix_o = features_pr.dot(np.linalg.inv(matrix_pr))

In [2]:
#np.round(matrix_o) == np.round(features.values)

### Вывод

Создана случайная матрица для шифрования признаков, а также сравнены значения R2 двух моделей: без шифрования признаков и с шифрованием.

Качество моделей различается после 15 знака, чем можно пренебречь (скорее это погрешность, т.к. случайная матрица состоит из чисел с плавающей точкой).

## Вывод

При умножении признаков на обратную матрицу качество линейной регрессии не изменяется, что было доказано теоретически, используя формулу расчета весов линейной регрессии, а также сравнив 2 модели линейной регрессии (первая не была умножена на обратную матрицу, вторая была умножена на обратную матрицу).